version = "0.3.2"

[scripts]
## Builds Tailwind CSS for development (no purging)
build-tailwind-dev = [
  "npx tailwindcss --postcss -c ./tailwind.config.js -i ./input.scss -o ./.css/output.css -w",
]
## Builds Tailwind CSS for production (maximum purging and minification)
build-tailwind-prod = [
  "NODE_ENV=production npx --postcss tailwindcss -c ./tailwind.config.js -i ./input.scss -o ./.css/output.css --minify",
]
## Builds Tailwind CSS for development usage
setup.subcommands.tailwind = "./bin/bonnie build-tailwind-dev"
setup.subcommands.prompt-tailwind = "echo \"Have you installed the Tailwind CLI globally with 'npm i -g tailwindcss' or 'yarn global add tailwindcss'?\""
setup.order = """
tailwind {
    Failure => prompt-tailwind
}
"""

## Builds everything
build.cmd = [
  "bonnie build-tailwind-prod",
  "trunk build --public-url memory-game-rs",
]

## Runs the frontend, watching for changes (uses Trunk)
run.subcommands.tailwind = ["bonnie build-tailwind-dev"]
run.subcommands.frontend = [
  # "rm -rf target",
  "trunk --config Trunk.dev.toml serve --port 8080",
]
